### ISSUE TITLE
One of RECIEVER_EXPORTED or RECIEVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

### ISSUE THREAD

**Issue by nd0nd0** [dyte-io/react-native-samples#3]
Currently using 

"react-native": "0.73.2",
"@dytesdk/react-native-core": "^0.8.2",
"@dytesdk/react-native-ui-kit": "^1.7.0", on Windows 11.

However, I am facing challenges developing with Dyte. 

Error - One of RECIEVER_EXPORTED or RECIEVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
![error](https://github.com/dyte-io/react-native-samples/assets/70109131/73b6c20d-1a56-4e1f-9e29-d05936635fb6)

**Comment by mayankofficial999** [comment]
Hello @nd0nd0 
This issue has been resolved in the latest version of Dyte React Native SDKs.
The sample apps have been updated for the same.
